# Generated by Django 2.2.7 on 2019-11-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=20, null=True)),
                ('is_admin', models.BooleanField()),
            ],
            options={
                'db_table': 'user_details',
                'managed': True,
            },
        ),
    ]
