# Generated by Django 2.2.7 on 2019-12-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
